spring.cloud.stream:
  default.contentType: application/json
  bindings.input:
    destination: users
    group: emailGroup

---
spring.profiles: docker

server.port: 8080

spring.cloud.stream.kafka.binder.brokers: kafka:9092,kafka1:9091
