version: '2.1'

services:
  producer:
    build: services/micro-producer
    ports:
      - "8080:8080"
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_STREAM_DEFAULTBINDER=kafka
    depends_on:
      - kafka


  email-service:
    build: services/email-service
    mem_limit: 350m
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - MANAGEMENT_HEALTH_RABBIT_ENABLED=false
        - SPRING_CLOUD_STREAM_DEFAULTBINDER=kafka
        - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_PARTITIONED=false

    depends_on:
      - kafka


  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    mem_limit: 350m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    mem_limit: 350m
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper